# General settings
reset_persistent = true  # Whether to reset persistent data on startup

# Kubernetes StatefulSet settings
name_node_count = 2
data_node_count = 5
name_data_relationship = "rotate" # Can be rotate or split

# Cluster settings
heartbeat_interval_secs = 5
heartbeat_timeout_secs = 10

# Network settings
interface_listen_addr = "0.0.0.0"
interface_listen_port = 11780
hdfs_listen_addr = "0.0.0.0"
hdfs_listen_port = 11738

# Block settings
block_size = 4096
block_size_unit = "kb"

# File settings
file_replication_count = 3
file_hash_function = "sha256"
file_checksum_method = "majority"  # Can be either majority or primary
