# Resources
# https://docs.ruby-lang.org/en/master/OpenSSL/Digest.html


# Whether to reset persistent data on startup.
reset_persistent = true

# Location for setup files.
setup_location = "./hdfs_setup"

##############################################################################
##############################################################################

[nodeconfig]

# Where the app will be located in the container image file.
app_location = "/usr/src/app/"

# Where the shared filesystem would be located in the container image file.
shared_fs_location = "/usr/src/app/shared/"

# Where the node data folder would be located in the container image file.
data_location = "/usr/src/app/local/"

# File name where the node's state will be stored and retrieved.
node_state_filename = "node_state.toml"

# Where the block storage folder would be located in the container image file.
block_storage_location = "/usr/src/app/blockstore/"

##############################################################################
##############################################################################

# Kubernetes StatefulSet settings
[nodecount]

# Number of NameNodes in the cluster.
name_node_count = 2 

# Number of DataNodes in the cluster.
data_node_count = 5

##############################################################################
##############################################################################

# Cluster settings
[cluster]

# Interval between keep alive messages sent.
heartbeat_interval_secs = 5

# Timeout for waiting for heartbeat messages after usual interval passes.
heartbeat_timeout_secs = 10 

# How DataNode work is divided among NameNodes. Can be rotate or split.
name_data_relationship = "rotate" 

# Size of shared filesystem in [shared_filesystem_size_unit].
shared_filesystem_size = 1 

# Unit of shared filesystem size. Can be "b", "kb", "mb", or "gb".
shared_filesystem_size_unit = "gb" 

# Size of interface storage drive in [interface_storage_size_unit].
interface_storage_size = 250 

# Unit of storage. Can be "b", "kb", "mb", or "gb".
interface_storage_size_unit = "mb" 

# Size of NameNode storage drive in [namenode_storage_size_unit].
namenode_storage_size = 250 

# Unit of storage. Can be "b", "kb", "mb", or "gb".
namenode_storage_size_unit = "mb" 

# Size of DataNode storage drive in [datanode_storage_size_unit].
datanode_storage_size = 250 

# Unit of storage. Can be "b", "kb", "mb", or "gb".
datanode_storage_size_unit = "mb"

##############################################################################
##############################################################################

# Network settings
[network]

# Listening address for the interface.
interface_listen_addr = "0.0.0.0" 

# Listening Port for the interface.
interface_listen_port = 11780 

# Listening address for HDFS.
hdfs_listen_addr = "0.0.0.0" 

# Listening Port for HDFS. I wanted it to be 1738 for a joke but Windows
#	started yelling at me about "DON'T USE WELL KNOWN PORTS" or something smh.
hdfs_listen_port = 11738

##############################################################################
##############################################################################

# Security settings
[security]

# Whether to enable TLS for secure communication.
enable_tls = true 

# Size of the RSA key for TLS in bits.
tls_rsa_key_size = 2048 

# Version of the TLS certificate.
tls_cert_version = 2 

# Length of the TLS certificate serial number in bytes.
tls_cert_serial_length = 32 

# Validity period for the TLS certificate in days.
tls_cert_validity_days = 30 

# Hash function used for the TLS certificate digest. Use the ruby 
#	OpenSSL::Digest module linked at the to find available hash functions.
tls_cert_digest_hash = "SHA256"

##############################################################################
##############################################################################

# Block settings
[block]

# Size of each block in [block_size_unit].
block_size = 16

# Unit for block size, can be "b", "kb", "mb", or "gb".
block_size_unit = "kb" 

##############################################################################
##############################################################################

# File settings
[file]

# Number of replicas for each file.
file_replication_count = 3 

# Hash function used for file integrity.
file_hash_function = "sha256" 

# Can be either majority or primary.
file_checksum_method = "majority" 

# Size of each file chunk in [file_chunk_size_unit].
file_chunk_size = 4 

# Unit for chunk size. Can be "b", "kb", "mb", or "gb".
file_chunk_size_unit = "kb"
