# Kubernetes StatefulSet settings
interface_node_count = 2
name_node_count = 2
data_node_count = 5

# Cluster settings
heartbeat_interval_secs = 5
heartbeat_timeout_secs = 10

# Network settings
interface_port = 1780
hdfs_port = 1738

# Block settings
block_size = 4096
block_size_unit = "kb"

# File settings
file_replication_count = 3
file_hash_function = "sha256"
file_checksum_method = "majority"  # Can be either majority or primary
