# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chunk_transfer.proto for package 'chunktransfer'
# Original file comments:
#
# File: chunk_transfer.proto
# Overview: This file defines the ChunkTransferService and its RPC messages.
#
#

require 'grpc'
require_relative 'chunk_transfer_pb'

module Chunktransfer
  module ChunkTransferService
    # ChunkTransferService defines the RPC services available for all nodes.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chunktransfer.ChunkTransferService'

      # 1. Receive data in chunks
      rpc :ReceiveChunks, stream(::Chunktransfer::ChunkData), ::Chunktransfer::ReceiveChunksResponse
      # 2. Send data in chunks
      rpc :SendChunks, ::Chunktransfer::SendChunksRequest, stream(::Chunktransfer::ChunkData)
    end

    Stub = Service.rpc_stub_class
  end
end
