# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: datanode.proto for package 'datanode'
# Original file comments:
#
# File: datanode.proto
# Overview: This file defines the DataNodeService and its RPC messages.
#
#

require 'grpc'
require_relative 'datanode_pb'

module Datanode
  module DataNodeService
    # DataNodeService defines the RPC services available for DataNodes
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'datanode.DataNodeService'

      # 1. Receive block creation request from NameNode
      rpc :NameNodeCreateBlocks, ::Datanode::CreateBlocksRequest, ::Datanode::CreateBlocksResponse
      # 2. Receive block retrieval request from NameNode
      rpc :NameNodeRetrieveBlocks, ::Datanode::RetrieveBlocksRequest, ::Datanode::RetrieveBlocksResponse
      # 3. Receive block update request from NameNode
      rpc :NameNodeUpdateBlocks, ::Datanode::UpdateBlocksRequest, ::Datanode::UpdateBlocksResponse
      # 4. Receive block deletion request from NameNode
      rpc :NameNodeDeleteBlocks, ::Datanode::DeleteBlocksRequest, ::Datanode::DeleteBlocksResponse
      # 5. Recieve status request from NameNode
      rpc :NameNodeStatusRequest, ::Datanode::StatusRequest, ::Datanode::StatusResponse
    end

    Stub = Service.rpc_stub_class
  end
end
