# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datanode.proto

require 'google/protobuf'

require 'shared/core_messages_pb'


descriptor_data = "\n\x0e\x64\x61tanode.proto\x12\x08\x64\x61tanode\x1a\x1ashared/core_messages.proto\"(\n\x13\x43reateBlocksRequest\x12\x11\n\tblock_ids\x18\x01 \x03(\r\"e\n\x14\x43reateBlocksResponse\x12$\n\rresponse_info\x18\x01 \x01(\x0b\x32\r.ResponseInfo\x12\'\n\x11session_info_list\x18\x02 \x03(\x0b\x32\x0c.SessionInfo\"*\n\x15RetrieveBlocksRequest\x12\x11\n\tblock_ids\x18\x01 \x03(\r\"g\n\x16RetrieveBlocksResponse\x12$\n\rresponse_info\x18\x01 \x01(\x0b\x32\r.ResponseInfo\x12\'\n\x11session_info_list\x18\x02 \x03(\x0b\x32\x0c.SessionInfo\"(\n\x13UpdateBlocksRequest\x12\x11\n\tblock_ids\x18\x01 \x03(\r\"e\n\x14UpdateBlocksResponse\x12$\n\rresponse_info\x18\x01 \x01(\x0b\x32\r.ResponseInfo\x12\'\n\x11session_info_list\x18\x02 \x03(\x0b\x32\x0c.SessionInfo\"(\n\x13\x44\x65leteBlocksRequest\x12\x11\n\tblock_ids\x18\x01 \x03(\r\"U\n\x14\x44\x65leteBlocksResponse\x12$\n\rresponse_info\x18\x01 \x01(\x0b\x32\r.ResponseInfo\x12\x17\n\x0f\x64\x65letion_status\x18\x02 \x03(\x08\"H\n\rStatusRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\r\x12&\n\x0enode_telemetry\x18\x02 \x01(\x0b\x32\x0e.NodeTelemetry\"u\n\x0eStatusResponse\x12$\n\rresponse_info\x18\x01 \x01(\x0b\x32\r.ResponseInfo\x12&\n\x0enode_telemetry\x18\x02 \x01(\x0b\x32\x0e.NodeTelemetry\x12\x15\n\runused_blocks\x18\x03 \x01(\r2\xbf\x03\n\x0f\x44\x61taNodeService\x12U\n\x14NameNodeCreateBlocks\x12\x1d.datanode.CreateBlocksRequest\x1a\x1e.datanode.CreateBlocksResponse\x12[\n\x16NameNodeRetrieveBlocks\x12\x1f.datanode.RetrieveBlocksRequest\x1a .datanode.RetrieveBlocksResponse\x12U\n\x14NameNodeUpdateBlocks\x12\x1d.datanode.UpdateBlocksRequest\x1a\x1e.datanode.UpdateBlocksResponse\x12U\n\x14NameNodeDeleteBlocks\x12\x1d.datanode.DeleteBlocksRequest\x1a\x1e.datanode.DeleteBlocksResponse\x12J\n\x15NameNodeStatusRequest\x12\x17.datanode.StatusRequest\x1a\x18.datanode.StatusResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Datanode
  CreateBlocksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("datanode.CreateBlocksRequest").msgclass
  CreateBlocksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("datanode.CreateBlocksResponse").msgclass
  RetrieveBlocksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("datanode.RetrieveBlocksRequest").msgclass
  RetrieveBlocksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("datanode.RetrieveBlocksResponse").msgclass
  UpdateBlocksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("datanode.UpdateBlocksRequest").msgclass
  UpdateBlocksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("datanode.UpdateBlocksResponse").msgclass
  DeleteBlocksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("datanode.DeleteBlocksRequest").msgclass
  DeleteBlocksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("datanode.DeleteBlocksResponse").msgclass
  StatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("datanode.StatusRequest").msgclass
  StatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("datanode.StatusResponse").msgclass
end
