# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: file_transfer.proto for package 'filetransfer'
# Original file comments:
#
# File: file_transfer.proto
# Overview: This file defines the FileTransferService and its RPC messages.
#
#

require 'grpc'
require 'file_transfer_pb'

module Filetransfer
  module FileTransferService
    # FileTransferService defines the RPC services available for all nodes.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'filetransfer.FileTransferService'

      # 1. Receive file in chunks
      rpc :ReceiveFileChunks, stream(::Filetransfer::FileChunkData), ::Filetransfer::FileChunkResponse
      # 2. Send file in chunks 
      rpc :SendFileChunks, ::Filetransfer::FileChunkRequest, stream(::Filetransfer::FileChunkData)
    end

    Stub = Service.rpc_stub_class
  end
end
