# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_transfer.proto

require 'google/protobuf'

require 'shared/core_messages_pb'


descriptor_data = "\n\x13\x66ile_transfer.proto\x12\x0c\x66iletransfer\x1a\x1ashared/core_messages.proto\"B\n\rFileChunkData\x12\"\n\x0csession_info\x18\x01 \x01(\x0b\x32\x0c.SessionInfo\x12\r\n\x05\x63hunk\x18\x02 \x01(\x0c\"9\n\x11\x46ileChunkResponse\x12$\n\rresponse_info\x18\x01 \x01(\x0b\x32\r.ResponseInfo\"6\n\x10\x46ileChunkRequest\x12\"\n\x0csession_info\x18\x01 \x01(\x0b\x32\x0c.SessionInfo2\xbb\x01\n\x13\x46ileTransferService\x12S\n\x11ReceiveFileChunks\x12\x1b.filetransfer.FileChunkData\x1a\x1f.filetransfer.FileChunkResponse(\x01\x12O\n\x0eSendFileChunks\x12\x1e.filetransfer.FileChunkRequest\x1a\x1b.filetransfer.FileChunkData0\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Filetransfer
  FileChunkData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filetransfer.FileChunkData").msgclass
  FileChunkResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filetransfer.FileChunkResponse").msgclass
  FileChunkRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("filetransfer.FileChunkRequest").msgclass
end
