# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: interface.proto for package 'interface'
# Original file comments:
#
# File: interface.proto
# Overview: This file defines the InterfaceService and its RPC messages.
#
#

require 'grpc'
require_relative 'interface_pb'

module Interface
  module InterfaceService
    # InterfaceService defines the RPC services available for Interface Nodes.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'interface.InterfaceService'

      # 1. Receive heartbeat from NameNode
      rpc :NameNodeAlive, ::Interface::NameNodePing, ::Interface::NameNodePingResponse
    end

    Stub = Service.rpc_stub_class
  end
end
