# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: namenode.proto for package 'namenode'
# Original file comments:
#
# File: namenode.proto
# Overview: This file defines the NameNodeService and its RPC messages.
#
#

require 'grpc'
require_relative 'namenode_pb'

module Namenode
  module NameNodeService
    # NameNodeService defines the RPC services available for NameNodes
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'namenode.NameNodeService'

      # 1. Receive heartbeat from NameNode
      rpc :NameNodeAlive, ::Namenode::NameNodePing, ::Namenode::NameNodePingResponse
      # 2. Receive heartbeat from DataNode
      rpc :DataNodeAlive, ::Namenode::DataNodePing, ::Namenode::DataNodePingResponse
      # 3. Receive file creation request from InterfaceNode
      rpc :InterfaceCreateFile, ::Namenode::CreateFileRequest, ::Namenode::CreateFileResponse
      # 4. Receive file retrieval request from InterfaceNode
      rpc :InterfaceRetrieveFile, ::Namenode::RetrieveFileRequest, ::Namenode::RetrieveFileResponse
      # 5. Receive new file information and file update request from InterfaceNode
      rpc :InterfaceUpdateFile, ::Namenode::UpdateFileRequest, ::Namenode::UpdateFileResponse
      # 6. Receive file deletion request from InterfaceNode
      rpc :InterfaceDeleteFile, ::Namenode::DeleteFileRequest, ::Namenode::DeleteFileResponse
    end

    Stub = Service.rpc_stub_class
  end
end
