# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: namenode.proto for package 'namenode'

require 'grpc'
require 'namenode_pb'

module Namenode
  module NameNodeService
    # NameNode service definition
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'namenode.NameNodeService'

      # 1. Ingest file data from an interface node
      rpc :IngestFile, ::Namenode::IngestFileRequest, ::Namenode::IngestFileResponse
      # 2. Retrieve file on behalf of interface node
      rpc :RetrieveFile, ::Namenode::RetrieveFileRequest, ::Namenode::RetrieveFileResponse
    end

    Stub = Service.rpc_stub_class
  end
end
