# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/core_messages.proto

require 'google/protobuf'


descriptor_data = "\n\x1ashared/core_messages.proto\"0\n\x0cResponseInfo\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"Q\n\rNodeTelemetry\x12\x12\n\ntime_stamp\x18\x01 \x01(\x04\x12\x16\n\x0e\x61\x63tive_threads\x18\x02 \x01(\r\x12\x14\n\x0c\x61\x63tive_conns\x18\x03 \x01(\r\"l\n\x08MetaData\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x15\n\rcreation_time\x18\x02 \x01(\x04\x12\x13\n\x0bmodify_time\x18\x03 \x01(\x04\x12\x11\n\textention\x18\x04 \x01(\t\x12\x11\n\tbyte_size\x18\x05 \x01(\x04\"Q\n\x0c\x46ileInfoData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12!\n\tmeta_info\x18\x02 \x01(\x0b\x32\t.MetaDataH\x00\x88\x01\x01\x42\x0c\n\n_meta_info\"3\n\x0bSessionInfo\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08\x63hecksum\x18\x02 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

ResponseInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ResponseInfo").msgclass
NodeTelemetry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NodeTelemetry").msgclass
MetaData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MetaData").msgclass
FileInfoData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FileInfoData").msgclass
SessionInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SessionInfo").msgclass
