# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/core_messages.proto

require 'google/protobuf'


descriptor_data = "\n\x1ashared/core_messages.proto\"B\n\x0cResponseInfo\x12\x18\n\x10response_success\x18\x01 \x01(\x08\x12\x18\n\x10response_message\x18\x02 \x01(\t\"Q\n\rNodeTelemetry\x12\x12\n\ntime_stamp\x18\x01 \x01(\x04\x12\x16\n\x0e\x61\x63tive_threads\x18\x02 \x01(\r\x12\x14\n\x0c\x61\x63tive_conns\x18\x03 \x01(\r\";\n\x0bSessionInfo\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x18\n\x10session_checksum\x18\x02 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

ResponseInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ResponseInfo").msgclass
NodeTelemetry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NodeTelemetry").msgclass
SessionInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SessionInfo").msgclass
