# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: namenode.proto

require 'google/protobuf'


descriptor_data = "\n\x0enamenode.proto\x12\x08namenode\"k\n\x08Metadata\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x15\n\rcreation_time\x18\x02 \x01(\x03\x12\x13\n\x0bmodify_time\x18\x03 \x01(\x03\x12\x11\n\textention\x18\x04 \x01(\t\x12\x10\n\x08\x62ytesize\x18\x05 \x01(\x03\"S\n\x08\x46ileData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12$\n\x08metainfo\x18\x02 \x01(\x0b\x32\x12.namenode.Metadata\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\"5\n\x11IngestFileRequest\x12 \n\x04\x66ile\x18\x01 \x01(\x0b\x32\x12.namenode.FileData\"6\n\x12IngestFileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\'\n\x13RetrieveFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"l\n\x14RetrieveFileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12 \n\x04\x66ile\x18\x03 \x01(\x0b\x32\x12.namenode.FileData\x12\x10\n\x08\x63hecksum\x18\x04 \x01(\t2\xa9\x01\n\x0fNameNodeService\x12G\n\nIngestFile\x12\x1b.namenode.IngestFileRequest\x1a\x1c.namenode.IngestFileResponse\x12M\n\x0cRetrieveFile\x12\x1d.namenode.RetrieveFileRequest\x1a\x1e.namenode.RetrieveFileResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Namenode
  Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("namenode.Metadata").msgclass
  FileData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("namenode.FileData").msgclass
  IngestFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("namenode.IngestFileRequest").msgclass
  IngestFileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("namenode.IngestFileResponse").msgclass
  RetrieveFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("namenode.RetrieveFileRequest").msgclass
  RetrieveFileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("namenode.RetrieveFileResponse").msgclass
end
